<?php
header('Content-type:text/json');
$res = [
  'result' => '1', 
  'data' => [
  	"/site/getvericode"=>2,
	  "/site/addmobile"=>2,
    "/site/checkusername"=>1,
    "/site/addvericode"=>1,
	  "/site/checkvericode"=>1,
//	  "/site/mobilejoincheck"=>1,
    "/site/userjoin"=>1,
//    "/site/mobilejoin"=>1,
    "/site/getCitys"=>1,
    "/site/getDistricts"=>1,
    "/site/getlocation"=>1,
    "/site/loginusername"=>1,
    "/site/loginmobile"=>1,
    "/site/LoginVericode"=>1,

    "/user/list"=>2,
    "/user/listadmin"=>2,
    "/user/main"=>2,
    "/user/view"=>2,
    "/user/usergroups"=>2,
    "/user/useracts"=>2,
    "/user/checkuser"=>2,
    "/user/selectrefuser"=>2,
    "/user/myrecommends"=>2,
    "/user/update"=>2,
    "/user/updateone"=>2,
    "/user/updaterefuser"=>2,
    "/user/updateoneadmin"=>2,    
    "/user/updatelocations"=>2,
    "/user/updatewblocations"=>2,
    "/user/updatenewestmsg"=>2,
    "/user/updateuserlife"=>2,

    "/friend/listadmin"=>2,
    "/friend/add"=>2,
    "/friend/delete"=>2,

    "/chat/newmsgs"=>2,
    "/chat/sendprivatechatdata"=>2,
    "/chat/sendpublicchatdata"=>2,

    "/shop/list"=>2,
    "/shop/storelist"=>2,
    "/shop/grouplist"=>2,
    "/shop/mygroups"=>2,
    "/shop/newgroups"=>2,
    "/shop/storegroups"=>2,
    "/shop/actlist"=>2,
    "/shop/storegroupsadmin"=>2,
    "/shop/mygroupsadmin"=>2,

    "/shop/viewstore"=>2,
    "/shop/detail"=>2,
    "/shop/main"=>2,
    "/shop/viewact"=>2,

    "/shop/createstore"=>2,
    "/shop/creategroup"=>2,

    "/shop/update"=>2,
    "/shop/updateone"=>2,
    "/shop/updatepaycertified"=>2,
    "/shop/updatepromotion"=>2,
    "/shop/updatewblocations"=>2,
    "/shop/updatenewestmsg"=>2,
    "/shop/updateproducttype"=>2,

    "/shop/actcancel"=>2,
    "/shop/actjoin"=>2,
    "/shop/setgroupcaptain"=>2,


    "/group/grouplist"=>2,
    "/group/main"=>2,
    "/group/detail"=>2,
    "/group/update"=>2,
    "/group/updateone"=>2,
    "/group/updatepaycertified"=>2,
    "/group/viewact"=>2,
    "/group/actcancel"=>2,
    "/group/actjoin"=>2,

    "/enroll/listadmin"=>2,

    "/member/storemembers"=>2,
    "/member/storemembersadmin"=>2,
    "/member/joinstorelist"=>2,
    "/member/joinstorefromusers"=>2,
    "/member/joinstore"=>2,
    "/member/deletefromstore"=>2,
    "/member/leavestore"=>2,   
    "/member/adminuserleftmoney"=>2,
    "/member/adminuserintro"=>2,
    "/member/adminuserpaycertified"=>2,
    "/member/adminusercertified"=>2,
    "/member/adminusernickname"=>2,
    "/member/adminuserpayprice"=>2,
    "/member/joinedrooms"=>2,
    "/member/ismember"=>2,

    "/photo/list"=>2,
    "/photo/listadmin"=>2,
    "/photo/create"=>2,
    "/photo/delete"=>2, 
    "/photo/update"=>2,

    "/product/list"=>2,
    "/product/listadmin"=>2,
    "/product/view"=>2,
    "/product/create"=>2,
    "/product/update"=>2,
    "/product/delete"=>2,

    "/article/list"=>2,
    "/article/listadmin"=>2,
    "/article/view"=>2,
    "/article/create"=>2,
    "/article/update"=>2,
    "/article/delete"=>2,

    "/retweet/articlelist"=>2,
    "/retweet/productlist"=>2,
    "/retweet/friendlist"=>2,
    "/retweet/view"=>2,
    "/retweet/checkretweet"=>2,
    "/retweet/create"=>2,
    "/retweet/delete"=>2,
    
    "/comment/create"=>2,
    "/comment/payment"=>2,  

    "/app/list"=>2,
    "/app/listadmin"=>2,
    "/app/create"=>2,
    "/app/update"=>2,
    "/app/delete"=>2,
    "/app/addmyapp"=>2,
    "/app/deletemyapp"=>2,

    "/cashlog/myrefincomes"=>2,
  ]
];
echo json_encode($res);